//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LottoDemo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrawStatistic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrawStatistic()
        {
            this.WinningTickets = new HashSet<WinningTicket>();
        }
    
        public int ID { get; set; }
        public int WinningsTierID { get; set; }
        public int LottoDrawingID { get; set; }
    
        public virtual GameWinningsTier GameWinningsTier { get; set; }
        public virtual LottoDrawing LottoDrawing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WinningTicket> WinningTickets { get; set; }
    }
}
