//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LottoDemo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrawingNumbers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrawingNumbers()
        {
            this.LottoDrawing = new HashSet<LottoDrawing>();
            this.LottoTicket = new HashSet<LottoTicket>();
        }
    
        public int ID { get; set; }
        public byte One { get; set; }
        public byte Two { get; set; }
        public byte Three { get; set; }
        public Nullable<byte> Four { get; set; }
        public Nullable<byte> Five { get; set; }
        public Nullable<byte> Six { get; set; }
        public Nullable<byte> Seven { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LottoDrawing> LottoDrawing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LottoTicket> LottoTicket { get; set; }
    }
}
