//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LottoDemo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameWinningsTier
    {
        public int ID { get; set; }
        public int LottoGameID { get; set; }
        public byte BallsCount { get; set; }
        public byte BonnusBallCount { get; set; }
        public string TierName { get; set; }
        public double TierPercent { get; set; }
    
        public virtual LotteryGame LotteryGame { get; set; }
    }
}
