//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LottoDemo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameWinningsTier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameWinningsTier()
        {
            this.DrawStatistics = new HashSet<DrawStatistic>();
        }
    
        public int ID { get; set; }
        public int LottoGameID { get; set; }
        public byte BallsCount { get; set; }
        public byte BonnusBallCount { get; set; }
        public string TierName { get; set; }
        public double TierPercent { get; set; }
    
        public virtual LotteryGame LotteryGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrawStatistic> DrawStatistics { get; set; }
    }
}
