//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LottoDemo.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LotteryDemoDBEntities1 : DbContext
    {
        public LotteryDemoDBEntities1()
            : base("name=LotteryDemoDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Balance> Balances { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<DrawingNumber> DrawingNumbers { get; set; }
        public virtual DbSet<Jackpot> Jackpots { get; set; }
        public virtual DbSet<LotteryGame> LotteryGames { get; set; }
        public virtual DbSet<LottoDrawing> LottoDrawings { get; set; }
        public virtual DbSet<LottoTicket> LottoTickets { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
