//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LottoDemo.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LotteryDemoDBEntities : DbContext
    {
        public LotteryDemoDBEntities()
            : base("name=LotteryDemoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Balance> Balance { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<DrawingNumbers> DrawingNumbers { get; set; }
        public virtual DbSet<Jackpot> Jackpot { get; set; }
        public virtual DbSet<LotteryGame> LotteryGame { get; set; }
        public virtual DbSet<LottoDrawing> LottoDrawing { get; set; }
        public virtual DbSet<LottoTicket> LottoTicket { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
