//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LottoDemo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotteryGameSetting
    {
        public int ID { get; set; }
        public int LotteryGameID { get; set; }
        public int MinimalBallNumber { get; set; }
        public int MaximalBallNumber { get; set; }
        public double DrawingTimeInterval { get; set; }
        public int DrawingBallsCount { get; set; }
    
        public virtual LotteryGame LotteryGame { get; set; }
    }
}
